[build]
  command = "bun run build"
  publish = "dist"

# Remote image settings
[images]
  remote_images = [
    "https://same-assets.com/.*",
    "https://cdn.akamai.steamstatic.com/.*",
    "https://cdn.cloudflare.steamstatic.com/.*",
    "https://community.cloudflare.steamstatic.com/.*",
    "https://ui-avatars.com/.*"
  ]

# Redirect for Single Page Application
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Image optimization settings
[build.processing]
  skip_processing = false

[build.processing.images]
  compress = true

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; img-src 'self' https://same-assets.com https://cdn.akamai.steamstatic.com https://cdn.cloudflare.steamstatic.com https://community.cloudflare.steamstatic.com https://ui-avatars.com https:; font-src 'self' https://fonts.googleapis.com https://fonts.gstatic.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; script-src 'self' 'unsafe-inline'; connect-src 'self';"
